### ISSUE TITLE
JIT compilation fails + parameter parallelism support?

### ISSUE THREAD

**Issue by utkarsh530** [martenlienen/torchode#9]
Hi,
I was trying out the package and try to solve the Lorenz problem over different parameters. Is there a way can I do this? I only saw examples where parallelism is done with multiple initial conditions. I tried doing `vmap` from `functorch`, but it just fails.

Example:

```
import torch
import torchode as to
from functorch import vmap

def f(t, y, k):
    x, y, z = y[..., 0] , y[..., 1], y[..., 2]
    return torch.stack((10*(y-x), k * x - y - x * z, x * y - (8/3)*z), dim = -1)

y0 = torch.tensor([[1.0, 0.0, 0.0]])
n_steps = 1000
t_eval = torch.stack((torch.linspace(0, 1, n_steps),))
term = to.ODETerm(f, with_args = True)
step_method = to.Tsit5(term = term)
controller = to.FixedStepController()
dt0 = torch.tensor([0.001])

solver = to.AutoDiffAdjoint(step_method, controller)

jit_solver = torch.jit.script(solver) # Fails

numberOfParameters = 10000
parameterList = torch.linspace(0.0,21.0,numberOfParameters)
sol = solver.solve(to.InitialValueProblem(y0 = y0, t_eval = t_eval), args = parameterList[-1], dt0 = dt0)
psol = lambda p : solver.solve(to.InitialValueProblem(y0 = y0, t_eval = t_eval), args = p, dt0 = dt0)
vmap(psol)(parameterList) # Fails
```

Moreover, I am not able to JIT compile my solver. Stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 476, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 538, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 516, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torch/jit/_recursive.py", line 393, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:
 method 'vf' is called recursively. Recursive calls are not supported:
  File "/home/utkarsh/.conda/envs/venv_torch/lib/python3.10/site-packages/torchode/single_step_methods/runge_kutta.py", line 200

            if f0 is None:
                prev_vf1 = term_.vf(problem.t_start, problem.y0, stats, args)
                           ~~~~~~~~ <--- HERE
            else:
                prev_vf1 = f0
```

**Comment by martenlienen** [comment]
To make your code JIT compilable, requires it to be written in TorchScript. The only way to pass arbitrary values in TorchScript is to treat them as `Any`, which is why the extra argument of `f` is of type `Any`. But if you don't declare a parameter type, the JIT compiler automatically infers `torch.Tensor` which leads to the JIT error you observe. To fix it, do
```python
from typing import Any

def f(t, y, k: Any):
    assert isinstance(k, torch.Tensor)
    x, y, z = y[..., 0], y[..., 1], y[..., 2]
    return torch.stack((10 * (y - x), k * x - y - x * z, x * y - (8 / 3) * z), dim=-1)
```

Regarding your second problem, torchode is unfortunately not compatible with vmap, at least I have not tried it, even though it uses vmap internally in one specific case. One way to make it work, would be to parallelize it over the same initial conditions `numberOfParameter` times and then ensure that everything broadcasts correctly in `f` with `k`, i.e.
```python
y0 = torch.tensor([[1.0, 0.0, 0.0]]).expand((numberOfParameters, -1))
```
and similar for `t_eval` and `dt0`.

**Comment by utkarsh530** [comment]
Thanks for help!
